# Generated by Django 4.2.3 on 2023-08-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escaperoom', '0002_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Room_Description',
        ),
    ]
